services:
  db:
    image: postgres:13  # Cambia a la imagen de PostgreSQL
    environment:
      POSTGRES_DB: mutante
      POSTGRES_USER: user_mutantedb
      POSTGRES_PASSWORD: mutante_password
    ports:
      - "5433:5432"  # Cambia el puerto a 5432 para PostgreSQL
    networks:
      - mutant-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Cambia el volumen para PostgreSQL

  api:
    build: .
    environment:
      POSTGRES_HOST: db  # Cambia a POSTGRES_HOST
      POSTGRES_PORT: 5432  # Cambia a 5432
      POSTGRES_DB: mutante  # Cambia a POSTGRES_DB
      POSTGRES_USER: user_mutantedb  # Cambia a POSTGRES_USER
      POSTGRES_PASSWORD: mutante_password  # Cambia a POSTGRES_PASSWORD
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - mutant-network

networks:
  mutant-network:
    driver: bridge

volumes:
  postgres_data:  # Cambia el volumen para PostgreSQL